namespace SpriteKind {
    export const Bad = SpriteKind.create()
    export const Swarm = SpriteKind.create()
    export const Raven = SpriteKind.create()
    export const B1 = SpriteKind.create()
    export const B2 = SpriteKind.create()
    export const Dartino1 = SpriteKind.create()
    export const Fishy = SpriteKind.create()
    export const Annoying = SpriteKind.create()
    export const AnnoyingMuch = SpriteKind.create()
    export const Button = SpriteKind.create()
    export const S = SpriteKind.create()
    export const NPC = SpriteKind.create()
    export const colouredButton = SpriteKind.create()
}